# Generated by Django 3.1.6 on 2021-02-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='checked',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='choices',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questoins',
            name='question',
            field=models.TextField(null=True),
        ),
    ]
