# Generated by Django 3.1.6 on 2021-02-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20210218_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='exam',
            field=models.TextField(null=True),
        ),
    ]
