# Generated by Django 3.1.6 on 2021-02-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_exams_exam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questoins',
            new_name='Questions',
        ),
    ]
