# Generated by Django 3.1.6 on 2021-02-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('exam', '0006_auto_20210221_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='group',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
