# Generated by Django 3.1.6 on 2021-02-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_exams_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams',
            name='examiner',
        ),
    ]
