# Generated by Django 3.1.6 on 2021-02-22 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_remove_exams_examiner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='examiner',
        ),
        migrations.RemoveField(
            model_name='examiner',
            name='dateOfParticipation',
        ),
        migrations.RemoveField(
            model_name='exams',
            name='group',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='examiner',
        ),
        migrations.AddField(
            model_name='exams',
            name='examiner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.examiner'),
        ),
        migrations.AddField(
            model_name='exams',
            name='status',
            field=models.CharField(choices=[('Participated', 'Participated'), ('Unparticipated', 'Unparticipated')], max_length=200, null=True),
        ),
    ]
