# Generated by Django 3.1.6 on 2021-02-23 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('exam', '0009_auto_20210222_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.TextField(null=True)),
                ('status', models.CharField(choices=[('Participated', 'Participated'), ('Unparticipated', 'Unparticipated')], max_length=200, null=True)),
                ('examiner_group', models.ManyToManyField(null=True, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.examiner')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Choices',
            new_name='Choice',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.DeleteModel(
            name='Exams',
        ),
        migrations.AlterField(
            model_name='question',
            name='exams',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
        ),
    ]
