# Generated by Django 3.1.6 on 2021-02-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('exam', '0010_auto_20210223_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examiner',
            name='user',
        ),
        migrations.DeleteModel(
            name='QuestionResult',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='user',
        ),
        migrations.AddField(
            model_name='examresult',
            name='choice',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='examiner_group',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('Participated', 'Participated'), ('Unparticipated', 'Unparticipated')], default='Unparticipated', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Examiner',
        ),
    ]
