# Generated by Django 3.1.6 on 2021-02-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_auto_20210224_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='test',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
