# Generated by Django 3.1.6 on 2021-02-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_examresult_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='test',
        ),
        migrations.AddField(
            model_name='examresult',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
