# Generated by Django 3.1.6 on 2021-02-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_auto_20210224_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='choice_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='exam_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='question_id',
            field=models.IntegerField(null=True),
        ),
    ]
