# Generated by Django 3.1.6 on 2021-02-25 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0014_auto_20210224_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='status',
        ),
        migrations.CreateModel(
            name='examStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Participated', 'Participated'), ('Unparticipated', 'Unparticipated')], default='Unparticipated', max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userExam', models.ManyToManyField(to='exam.Exam')),
            ],
        ),
    ]
