# Generated by Django 3.1.6 on 2021-02-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_auto_20210226_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examstatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='examstatus',
            name='userExam',
        ),
        migrations.AddField(
            model_name='examstatus',
            name='exam_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='examstatus',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
