# Generated by Django 3.1.6 on 2021-02-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_auto_20210226_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examstatus',
            name='status',
            field=models.CharField(default='Participated', max_length=200, null=True),
        ),
    ]
